
export const USER_DETAIL="userdetail";
export const NOTIFYSUCC="notifysuccess";
export const NOTIFYCLEAR="notifyclear";
export const NOTIFYERROR="notifyserror";
export const TEMPORARY="temporary";
export const TEMPORARYCLEAR="temporaryclear";
export const USERS="users";
export const PRE_REGISTER="pre-register";
export const GEO="geo";
export const GeoActive = "geoactive";
export const MAIN_COURSE="main_course";
export const NEWCONNECT="newconnect";
export const FILTERCARDS="FILTERCARDS"
export const FINDCARDS="FINDCARD";
export const GETREPORTCARDS="GETREPORTCARDS";
export const  REPORTCARD="reportcard"
export const GETCARDS="GETCARDS";
export const ADDCARD="ADDCARD";
export const VERIFIEDCARD="verifiedcard"

export const MESSAGEBOX="messagebox"
export const MATCHCARDS="MATCHCARDS"
export const COURSESP="coursep";
export const API="";
export const SEARCRESULTS="SEARCRESULTS"
export const ipgeoAPI="4ba870a05f5c45f000f0f7662999a397ce43b3c54b1e9cdb22407272";
export const IPUB="MjA5MjA6b0RqM3AyUFhVOHp4RFg5VldWbmdvbXRpNWJiRjg3cWw";
export const COMPLETEDQUIZES="completedquize"
export const FEEDBACK="feedback"
export const FEEDRETURN="feedreturn"
export const FEEDRETURNCLEAR="feedreturnclear"
export const SUMMARY="summary"